"""
VidSummarize - PDF Generation Module
Handles creation of professional PDF documents for transcripts and summaries
"""

from reportlab.lib.pagesizes import A4, letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from datetime import datetime
import os
import textwrap


class PDFGenerator:
    """Handles PDF generation for transcripts and summaries"""
    
    def __init__(self):
        """Initialize PDF generator"""
        self.page_size = A4
        self.styles = getSampleStyleSheet()
        self.registered_fonts = self._register_fonts()
        self.font_title = self._get_font_or_fallback("NotoSans-Bold", "Helvetica-Bold")
        self.font_body = self._get_font_or_fallback("NotoSans", "Helvetica")
        self._create_custom_styles()
    
    def _create_custom_styles(self):
        """Create custom paragraph styles"""
        # Title style
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor='#4f46e5',
            spaceAfter=30,
            alignment=TA_CENTER,
            fontName=self.font_title
        ))
        
        # Subtitle style
        self.styles.add(ParagraphStyle(
            name='CustomSubtitle',
            parent=self.styles['Normal'],
            fontSize=12,
            textColor='#64748b',
            spaceAfter=20,
            alignment=TA_CENTER,
            fontName=self.font_body
        ))
        
        # Metadata style
        self.styles.add(ParagraphStyle(
            name='Metadata',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor='#64748b',
            spaceAfter=10,
            fontName=self.font_body
        ))
        
        # Body text style
        self.styles.add(ParagraphStyle(
            name='CustomBody',
            parent=self.styles['BodyText'],
            fontSize=11,
            leading=16,
            alignment=TA_JUSTIFY,
            spaceAfter=12,
            fontName=self.font_body
        ))
    
    def generate_transcript_pdf(self, transcript_text, output_path, metadata=None):
        """
        Generate PDF document for transcript
        
        Args:
            transcript_text (str): Full transcript text
            output_path (str): Path to save PDF
            metadata (dict): Optional metadata (language, duration, etc.)
            
        Returns:
            bool: Success status
        """
        try:
            print(f"[PDFGenerator] Creating transcript PDF: {output_path}")
            
            # Create PDF document
            doc = SimpleDocTemplate(
                output_path,
                pagesize=self.page_size,
                rightMargin=72,
                leftMargin=72,
                topMargin=72,
                bottomMargin=18
            )
            
            # Container for PDF elements
            story = []
            
            self._apply_language_fonts(metadata.get('language') if metadata else None)

            # Add title
            title = Paragraph("Video Transcript", self.styles['CustomTitle'])
            story.append(title)
            story.append(Spacer(1, 0.2 * inch))
            
            # Add subtitle
            subtitle = Paragraph(
                "Generated by VidSummarize - AI-Powered Transcription",
                self.styles['CustomSubtitle']
            )
            story.append(subtitle)
            story.append(Spacer(1, 0.3 * inch))
            
            # Add metadata if provided
            if metadata:
                story.extend(self._add_metadata(metadata))
                story.append(Spacer(1, 0.3 * inch))
            
            # Add separator line
            story.append(Spacer(1, 0.1 * inch))
            
            # Add transcript text
            # Split into paragraphs
            paragraphs = transcript_text.split('\n\n')
            if len(paragraphs) == 1:
                # If no double newlines, split by single newlines
                paragraphs = transcript_text.split('\n')
            
            for para in paragraphs:
                if para.strip():
                    p = Paragraph(para.strip(), self.styles['CustomBody'])
                    story.append(p)
                    story.append(Spacer(1, 0.1 * inch))
            
            # Add footer
            story.append(Spacer(1, 0.5 * inch))
            footer_text = f"Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}"
            footer = Paragraph(footer_text, self.styles['Metadata'])
            story.append(footer)
            
            # Build PDF
            doc.build(story)
            
            print(f"[PDFGenerator] Transcript PDF created successfully")
            return True
            
        except Exception as e:
            print(f"[PDFGenerator] Error creating transcript PDF: {str(e)}")
            return False
    
    def generate_summary_pdf(self, summary_text, output_path, metadata=None):
        """
        Generate PDF document for summary
        
        Args:
            summary_text (str): Summary text
            output_path (str): Path to save PDF
            metadata (dict): Optional metadata
            
        Returns:
            bool: Success status
        """
        try:
            print(f"[PDFGenerator] Creating summary PDF: {output_path}")
            
            # Create PDF document
            doc = SimpleDocTemplate(
                output_path,
                pagesize=self.page_size,
                rightMargin=72,
                leftMargin=72,
                topMargin=72,
                bottomMargin=18
            )
            
            # Container for PDF elements
            story = []
            
            self._apply_language_fonts(metadata.get('language') if metadata else None)

            # Add title
            title = Paragraph("Video Summary", self.styles['CustomTitle'])
            story.append(title)
            story.append(Spacer(1, 0.2 * inch))
            
            # Add subtitle
            subtitle = Paragraph(
                "AI-Generated Summary using BART Neural Network",
                self.styles['CustomSubtitle']
            )
            story.append(subtitle)
            story.append(Spacer(1, 0.3 * inch))
            
            # Add metadata if provided
            if metadata:
                story.extend(self._add_metadata(metadata))
                story.append(Spacer(1, 0.3 * inch))
            
            # Add separator
            story.append(Spacer(1, 0.1 * inch))
            
            # Add summary section header
            summary_header = Paragraph("Summary", self.styles['Heading2'])
            story.append(summary_header)
            story.append(Spacer(1, 0.2 * inch))
            
            # Add summary text
            paragraphs = summary_text.split('\n\n')
            if len(paragraphs) == 1:
                paragraphs = summary_text.split('\n')
            
            for para in paragraphs:
                if para.strip():
                    p = Paragraph(para.strip(), self.styles['CustomBody'])
                    story.append(p)
                    story.append(Spacer(1, 0.1 * inch))
            
            # Add footer
            story.append(Spacer(1, 0.5 * inch))
            footer_text = f"Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}"
            footer = Paragraph(footer_text, self.styles['Metadata'])
            story.append(footer)
            
            # Build PDF
            doc.build(story)
            
            print(f"[PDFGenerator] Summary PDF created successfully")
            return True
            
        except Exception as e:
            print(f"[PDFGenerator] Error creating summary PDF: {str(e)}")
            return False
    
    def _add_metadata(self, metadata):
        """
        Create metadata elements for PDF
        
        Args:
            metadata (dict): Metadata dictionary
            
        Returns:
            list: List of PDF elements
        """
        elements = []
        
        # Create metadata section
        if metadata.get('language'):
            lang_text = f"<b>Language:</b> {metadata['language']}"
            elements.append(Paragraph(lang_text, self.styles['Metadata']))
        
        if metadata.get('duration'):
            duration = metadata['duration']
            minutes = int(duration // 60)
            seconds = int(duration % 60)
            duration_text = f"<b>Duration:</b> {minutes}m {seconds}s"
            elements.append(Paragraph(duration_text, self.styles['Metadata']))
        
        if metadata.get('word_count'):
            word_text = f"<b>Word Count:</b> {metadata['word_count']:,}"
            elements.append(Paragraph(word_text, self.styles['Metadata']))
        
        if metadata.get('date'):
            date_text = f"<b>Processed:</b> {metadata['date']}"
            elements.append(Paragraph(date_text, self.styles['Metadata']))
        
        return elements
    
    def _register_fonts(self):
        """Register Unicode-capable fonts if available on disk"""
        candidates = {
            "NotoSans": ["NotoSans-Regular.ttf", "NotoSans-Regular.otf"],
            "NotoSans-Bold": ["NotoSans-Bold.ttf", "NotoSans-Bold.otf"],
            "NotoSansDevanagari": ["NotoSansDevanagari-Regular.ttf"],
            "NotoSansDevanagari-Bold": ["NotoSansDevanagari-Bold.ttf"],
            "NotoSansTamil": ["NotoSansTamil-Regular.ttf"],
            "NotoSansTamil-Bold": ["NotoSansTamil-Bold.ttf"],
            "NotoSansTelugu": ["NotoSansTelugu-Regular.ttf"],
            "NotoSansTelugu-Bold": ["NotoSansTelugu-Bold.ttf"]
        }

        search_dirs = []
        font_dir_env = os.getenv("VIDSUMMARIZE_FONT_DIR")
        if font_dir_env:
            search_dirs.append(font_dir_env)

        base_dir = os.path.dirname(os.path.abspath(__file__))
        search_dirs.extend([
            os.path.join(base_dir, "fonts"),
            os.path.join(base_dir, "static", "fonts"),
            os.path.join(os.getcwd(), "fonts"),
            os.path.join(os.getcwd(), "static", "fonts")
        ])

        registered = set()
        for font_name, filenames in candidates.items():
            for directory in search_dirs:
                for filename in filenames:
                    font_path = os.path.join(directory, filename)
                    if os.path.exists(font_path):
                        try:
                            pdfmetrics.registerFont(TTFont(font_name, font_path))
                            registered.add(font_name)
                        except Exception as e:
                            print(f"[PDFGenerator] Font register failed: {font_path} ({e})")
                        break
                if font_name in registered:
                    break

        if not registered:
            print("[PDFGenerator] Unicode fonts not found; using Helvetica fallback")
        else:
            print(f"[PDFGenerator] Registered fonts: {sorted(registered)}")

        return registered

    def _get_font_or_fallback(self, preferred, fallback):
        """Get preferred font or fallback to standard font"""
        return preferred if preferred in self.registered_fonts else fallback

    def _select_body_font(self, language_code):
        """Select appropriate font based on language"""
        if not language_code:
            return self.font_body
        lang = str(language_code).lower()
        lang_map = {
            "hi": "NotoSansDevanagari",
            "mr": "NotoSansDevanagari",
            "ta": "NotoSansTamil",
            "te": "NotoSansTelugu"
        }
        preferred = lang_map.get(lang)
        if preferred and preferred in self.registered_fonts:
            return preferred
        return self.font_body

    def _apply_language_fonts(self, language_code):
        """Apply language-specific fonts to styles"""
        body_font = self._select_body_font(language_code)
        self.styles['CustomBody'].fontName = body_font
        self.styles['Metadata'].fontName = body_font


# Test function
if __name__ == "__main__":
    print("=" * 60)
    print("VidSummarize - PDF Generator Test")
    print("=" * 60)
    
    # Test data
    test_transcript = """
    This is a sample transcript for testing PDF generation. 
    The transcript contains the full text of what was spoken in the video.
    
    It includes multiple paragraphs to test formatting and layout.
    Each paragraph should be properly spaced and justified.
    
    This is another paragraph to demonstrate the PDF generation capabilities.
    The system should handle long texts and maintain proper formatting throughout.
    """
    
    test_summary = """
    This is a test summary. It provides a concise overview of the main points 
    discussed in the video. The summary is generated using AI and captures 
    the essential information in a brief format.
    """
    
    test_metadata = {
        'language': 'English',
        'duration': 180.5,
        'word_count': 287,
        'date': datetime.now().strftime('%B %d, %Y')
    }
    
    try:
        generator = PDFGenerator()
        print("\n✅ PDF Generator initialized successfully!")
        
        # Test transcript PDF
        print("\nGenerating test transcript PDF...")
        success = generator.generate_transcript_pdf(
            test_transcript,
            'test_transcript.pdf',
            test_metadata
        )
        
        if success:
            print("✅ Test transcript PDF created: test_transcript.pdf")
        else:
            print("❌ Failed to create transcript PDF")
        
        # Test summary PDF
        print("\nGenerating test summary PDF...")
        success = generator.generate_summary_pdf(
            test_summary,
            'test_summary.pdf',
            test_metadata
        )
        
        if success:
            print("✅ Test summary PDF created: test_summary.pdf")
        else:
            print("❌ Failed to create summary PDF")
        
    except Exception as e:
        print(f"\n❌ Error: {str(e)}")
    
    print("\n" + "=" * 60)
    print("PDF Generator test complete!")
    print("Check for test_transcript.pdf and test_summary.pdf")
    print("=" * 60)